baseURL: "/"
languageCode: "en-za"
title: "George Business Directory"

enableRobotsTXT: true

params:
  town: "George, Western Cape"
  feedbackFormUrl: "https://forms.gle/WsUjtGi1ayK8Mvpq5"
  feedbackPriceUpdateUrl: ""
  feedbackIncorrectListingUrl: ""
  feedbackAddStationUrl: ""
  ownerEmail: ""
  analytics:
    goatcounterDomain: ""

permalinks:
  coffee: "/coffee/:slug/"
  bicycle: "/bicycle/:slug/"
  medical: "/medical/:slug/"
  animal-services: "/animal-services/:slug/"

markup:
  goldmark:
    renderer:
      unsafe: true
